name: 'Supported legacy versions'
description: 'Get the backend versions the app will run on except the latest one'
inputs:
    instance-url-latest:
        description: 'The URL to the instance with the latest version. Required if maxDHIS2Version is not specified in d2.config'
        required: false
    username:
        description: 'The DHIS2 username for authentication. Required if maxDHIS2Version is not specified in d2.config'
        required: false
    password:
        description: 'The DHIS2 password for authentication. Required if maxDHIS2Version is not specified in d2.config'
        required: false
    config-dir:
        description: 'Optionally specifiy a relative directory for the d2.config file'
        default: ./
outputs:
    versions:
        description: 'An array containing the supported legacy versions'
        value: ${{ steps.legacy-versions.outputs.versions }}
runs:
    using: 'composite'
    steps:
        - run: cp -r $GITHUB_ACTION_PATH/.github/actions ./action-supported-legacy-versions
          shell: bash

        - uses: ./action-supported-legacy-versions/precheck-max-version
          id: precheck
          with:
              config-dir: ${{ inputs.config-dir }}

        - if: steps.precheck.outputs.max-version == null
          uses: dhis2/action-instance-version@v1
          id: instance-version-latest
          with:
              instance-url: ${{ inputs.instance-url-latest }}
              username: ${{ inputs.username }}
              password: ${{ inputs.password }}

        - uses: ./action-supported-legacy-versions/legacy-versions
          id: legacy-versions
          with:
              config-dir: ${{ inputs.config-dir }}
              latest-version: ${{ steps.precheck.outputs.max-version || steps.instance-version-latest.outputs.version }}
